name: Run CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install using Poetry
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run ruff format --check src
          poetry run ruff check src
          poetry run mypy src
          poetry run muffin --version
